project:
  type: website

website:
  title: "Jonathan Leon"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: About
        href: about.qmd
      - text: Projects
        menu:
          - text: Project 1
            href: projects/project1.qmd

format:
  html:
    theme:
      - sandstone
      - brand
    css: styles.css
    toc: false



